#pragma once

#define GEMSGUI_VERSION "3.10.0"
#define GEMSGUI_VERSION_HASH "718a13fc"
#define GEMSGUI_GIT_BRANCH "fix_icons"
#define GEMSGUI_OSX "Linux"
#define GEMSGUI_COMPILER_ID "GNU"
#define GEMSGUI_COMPILER_VERSION "13.3.0"
#define GEMSGUI_QT_VERSION "6.8.2"
