name: GEMSGUI

channels:
  - conda-forge
  - defaults

dependencies:
  - cmake
  - git
  - gcc_linux-64  # [linux] 
  - gxx_linux-64  # [linux] 
  - sysroot_linux-64=2.28  # [linux] 
  - make  # [unix]
  - ninja
  - 7zip  # [win]
  - gems3k>=4.4.2
  #- thermofun>=0.4.3
  - cppzmq
  - mesa-libgl-devel-cos7-x86_64 # [unix]
  - qt6-main=6.8.2
  - qt6-charts=6.8.2
  #- eigen=3.4.0
  #- nlohmann_json
  #- spdlog
  - python>=3.7
  - pytest
